---

- name: Install linux headers
  apt:
    name="{{ pkgs }}"
    state="present"
    update_cache=True
    install_recommends=False
  vars:
    pkgs:
    - linux-headers-amd64
    - dkms

- name: download rtl8812au-dkms deb
  get_url:
    url: http://http.kali.org/pool/contrib/r/realtek-rtl88xxau-dkms/realtek-rtl88xxau-dkms_5.2.20.2~20190210-0kali1_all.deb
    dest: /root/realtek-rtl88xxau-dkms_5.2.20.2~20190210-0kali1_all.deb
    mode: 0644
    checksum: sha256:47e7c0e06fea088ec9ee83ad2f434d2799c28ae5052edc0cafc83b77b06d734e

- name: Install rtl8812au package
  apt:
    deb="/root/realtek-rtl88xxau-dkms_5.2.20.2~20190210-0kali1_all.deb"
    state="present"
    update_cache=True
    install_recommends=False

